//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_tipa
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRooms
    {
        public int id { get; set; }
        public string floor { get; set; }
        public Nullable<int> number { get; set; }
        public string category { get; set; }
        public string status { get; set; }
        public decimal price { get; set; }
    }
}
